name: ATM Application CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Run application with secrets
          env:
            ATM_API_KEY: ${{ secrets.ATM_API_KEY }}
            ATM_FROM_EMAIL: ${{ secrets.ATM_FROM_EMAIL }}
            ATM_EMAIL_PASSWORD: ${{ secrets.ATM_EMAIL_PASSWORD }}
          run: |
            echo "Using ATM_API_KEY: $ATM_API_KEY"
            echo "Using ATM_FROM_EMAIL: $ATM_FROM_EMAIL"
            java -cp "build:lib/*" atmfree.AtmFeeApplication
